[connections.gsheets]
spreadsheet = "1t_hRvnpf_UaIH9_ZXvItlrsHVf2UaLrxQSNcpZQoQVA"

[connections.gsheets.credentials]
type= "service_account"
project_id= "apt-footing-474320-a0"
private_key_id= "696ec2e739fce1994f0d643ea25a45d35c391e7f"
private_key= "-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCeJRJSFOGGyf/n
hEspmFflV7FOZZZ7GPfTO3y0GLLTuWkvXcXSPavnKf3lJmlqbg8IW52JrafZRGVm
JdknQHM1VkxVQEzGZLjZnN1GGZVEPnc1MnAAvJHWqylYJp0S8wffVTCPqCkqqEy+
FXtNMXQP7bSArzynDaXyhmI2wxiEOTQgJsCNRtgcfQTDe/51txPmEzAV069/HS27
RFVPh+YXK/c2vuKauk6W88tYTSk6BY6F7nAEANV6Luy624c9WUSljlWmYtuqRwfb
w9XWV8sgM3kJwrEw4QcgDvt5pefcI6Tgud11U2BQ/3tX+pLMamhrFVJApcZxlXG/
23j+kMqvAgMBAAECggEACjE/IYgpUuEbplBknGfY/mCCU8MAtFVTH6DoCXQauReW
5mUc9fm15b5TQpy7qDmIrClkxAtWU+PwbxQbD0hm7yCX5y9aOLfOzBkBOok1PBfp
4fAAFPlnotYW4jthiJJI8cVmov5GYkfvjkQJ1YX4QiXiqh/hK65vAWxU0c0NfElY
3rPg/qLn2yiy/GLulUibjMSXG21ebFVO705VE/YDJS3VPtdx1oHYa4NSxdACmKyr
cACgRK6qLABSaBSAd/MPSUY4FD3a3v+SzqNO0/rNXhOfpaoWhHIs+mdtVTkqKKe2
pqPL4VRlPkC6pylWGjQ9QDZGLHSBsIAGiL9f2rs7xQKBgQDXwfC5S05RKcKJSVUZ
BML5jYr/Z0Au8bC8Wkz28giv7uF5mrOR9I5hetcaiWEe3fnnRwvtd1/mXJEraTu5
w4gf/r8y7U+j/HFfBc8VhZ4wYESQT7PeemYFJ/Eob0EGwvoAoPewT9r4zU+SJjvY
DNIqTHI/2qwaZr7X/mNnTQUfVQKBgQC7pDgL+WDGLdaqpUJ2/+MSaeXeO7G+p1wu
/thf2kECv/Rw+3iFRS/cLadQr2YKa0hTX5GxP+maMXStpbGWmQx+r3c4zAJUykNp
usQlM2xMLZ/+UPVtX5jANtyyQzRb+P9Wq0VfSs8CaReBroSuT6Z/nC0A4PLyIrcP
2t6XnJHZ8wKBgHmL0EkSm3QtymH85evKOuzLSFrJl+baUW5KkMEtaKd0M6GF/VNk
KjHQOg3BBu2Ur4wTAi0s6uGjlESYbAUimjUsFhpihlMji9q0Mw000QD/uqBxxiq3
WXHeJoVY55Eflid0hxTUZ89yGjmDQINd9afOmS5PylS1PR4BOY6gXRphAoGAUcqQ
X6/RXjFm7DVjFmoN+d3NRCSzIs7i4N1XRdjmE6PGkmUbMMRqy0ffMc1y5kHDYgw7
fo7EbeD24iZilambB7HGfyx2K62K2xB9JVYX89DDd+CkSousEsUXSGEA9sI/0vCP
Ka17NKrIg0+mKDEx+1gBSevEGoXFVBTsiBvIe78CgYABDEq8aE5OYqwFQ1HsFrA+
xtqYVmj+iP/kr0PfABxKKKoHWsnAGu4SeZXDUqzLwzxUezY/t0M+zx3cbOIFPM9c
gF5HsF4bS1VTXz1xU8lfPh/ac936BD4VBMk6VBBFBc2FbCZIV+jUlm5Y/GSUf9Mc
DaQPJQFj1KIr46Dpj/opKg==
-----END PRIVATE KEY-----"
client_email= "streamlit-gsheets@apt-footing-474320-a0.iam.gserviceaccount.com"
client_id= "112805078535342356090"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheets%40apt-footing-474320-a0.iam.gserviceaccount.com"
universe_domain= "googleapis.com"
